# Generated by Django 3.1 on 2020-08-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20200830_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
