# Generated by Django 3.1 on 2020-08-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduction',
            field=models.TextField(default=''),
        ),
    ]
